# Generated by Django 5.2.8 on 2025-12-08 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autovettura',
            fields=[
                ('targa', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="La targa deve essere nel formato 'AB 123 CD', con lettere maiuscole e senza spazi", regex='^[A-Z]{2}\\d{3}[A-Z]{2}$')])),
                ('marca', models.CharField(max_length=20)),
                ('modello', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meccanico',
            fields=[
                ('ID_meccanico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('ID_intervento', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('targa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='prima_app.autovettura')),
                ('meccanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='prima_app.meccanico')),
            ],
        ),
    ]
